starkware-libs/stwo-cairo-m31

runnair/crates/runner/src/memory/mod.rs
runnair/crates/runner/src/vm/assert.rs
runnair/crates/runner/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4)

feat: implement `assert_[ap/fp]_add_[ap/fp]_[ap/fp][_appp]` instructions

---

runnair/crates/runner/src/vm/add_ap.rs
runnair/crates/runner/src/vm/assert.rs
runnair/crates/runner/src/vm/jmp.rs
runnair/crates/runner/src/vm/operand.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/7)

refactor: change functions' visibility to minimal needed

---

crates/prover/src/cairo_air/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/9)

fix: fix master

---

crates/runnair/src/vm/assert.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/11)

refactor: tidy-up `define_assert`, as prep. for immediate support

---

crates/runnair/src/vm/assert.rs
crates/runnair/src/vm/call.rs
crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/8)

feat: implement `call_[abs/rel]_[ap/fp/imm]` and `ret` instructions

---

crates/runnair/src/vm/assert.rs
crates/runnair/src/vm/jmp.rs
crates/runnair/src/vm/jnz.rs
crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/10)

feat: implement `jnz_[ap/fp/imm]_[ap/fp][_appp]` instructions

---

crates/runnair/src/vm/jnz.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/15)

fix: fix `jnz` argument offsets

---

crates/runnair/src/vm/jnz.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/17)

fix: fix another offset but in `jnz`

---

crates/runnair/src/vm/add_ap.rs
crates/runnair/src/vm/call.rs
crates/runnair/src/vm/jmp.rs
crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/18)

fix: change state pointers to be addresses

---

crates/runnair/src/vm/assert.rs
crates/runnair/src/vm/jmp.rs
crates/runnair/src/vm/jnz.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/20)

fix: fix `jnz` and `assert` instruction bugs

---

crates/runnair/src/memory/relocatable.rs
crates/runnair/src/vm/call.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/19)

fix: fix `call` instruction bugs

---

crates/runnair/src/memory/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/21)

refactor: separate memory to areas

---

Cargo.lock
crates/runnair/Cargo.toml
crates/runnair/src/vm/mod.rs
crates/runnair/tests/data/fibonacci_compiled.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/22)

feat: add `Program` struct and its deserialization from compiled file

---

crates/runnair/src/lib.rs
crates/runnair/src/main.rs
crates/runnair/src/memory/mod.rs
crates/runnair/src/memory/relocatable.rs
crates/runnair/src/vm/deref.rs
crates/runnair/src/vm/jmp.rs
crates/runnair/src/vm/jnz.rs
crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/23)

refactor: make runner a library; fix visibility

---

crates/runnair/src/memory/mod.rs
crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/24)

feat: add VM c-tor for main execution

---

crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/25)

feat: add execution functionality to VM

---

crates/runnair/src/memory/relocatable.rs
crates/runnair/src/vm/hints.rs
crates/runnair/src/vm/mod.rs
crates/runnair/tests/data/fibonacci_compiled.json

Only trivial format for now (JSON); to-be-expanded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26)

feat: support fibonacci claim index assignment hint

---

crates/runnair/src/memory/mod.rs
crates/runnair/src/memory/relocatable.rs
crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/27)

refactor: segment area is vector

---

crates/runnair/src/main.rs
crates/runnair/src/utils.rs
crates/runnair/src/vm/hints.rs
crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/28)

refactor: add utils file

---

crates/runnair/src/memory/mod.rs
crates/runnair/src/utils.rs
crates/runnair/src/vm/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/29)

refactor: segments without hashmaps

---

crates/runnair/src/vm/hints.rs
crates/runnair/src/vm/mod.rs
crates/runnair/tests/data/fibonacci_compiled.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/30)

feat: add custom (de)serialization of hints

---

crates/runnair/src/utils.rs
crates/runnair/src/vm/assert.rs
crates/runnair/src/vm/call.rs
crates/runnair/src/vm/jnz.rs
crates/runnair/src/vm/mod.rs
crates/runnair/src/vm/operand.rs
crates/runnair/tests/data/fibonacci_compiled.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31)

feat: immediates segment

---

crates/prover/src/components/memory/addr_to_f31/prover.rs

Also use PackedSecureField instead of explicit `PackedQM31`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/33)

fix: `ClaimGenerator`'s values should be PackedQM31
